routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\FriendController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ReplyController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', [PostController::class, 'index'])->name('home');
Route::get('/home', [PostController::class, 'index'])->name('home');

Route::middleware('auth:web')->group(function () {
    Route::resource('users', UserController::class)->only(['index', 'show', 'update']);
    Route::put('users/{user}/banner', [UserController::class, 'addBanner']);
    Route::get('profile/edit', [ProfileController::class, 'edit']); //OK
    Route::put('profile/{profile}', [ProfileController::class, 'update']); //OK
    Route::put('profile/{profileId}/image', [ProfileController::class, 'upload']);
    Route::delete('/friends/{userSlug}', [FriendController::class, 'unfriend']);

    Route::get('posts', [PostController::class, 'show']);
    Route::post('posts/{post}/comments', [CommentController::class, 'store']);
    Route::post('comments/{comment}/reply', [ReplyController::class, 'store']);
    Route::get('comments/{comment}', [ReplyController::class, 'show']);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'DR Social Spot') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Courgette&family=DM+Serif+Display&family=Lato&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css_after')
</head>
<body>
    <div id="app" class="font-sans main-body">
       @include('layouts.nav')

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
@yield('js_after')
</html>

resources/views/layouts/nav.blade.php
<nav class="flex items-center justify-between flex-wrap bg-transparent text-gray-900 p-6 font-sans text-3xl">
    <a class="flex items-center flex-no-shrink mr-6 cursor-pointer fixed" href="/home">
        <span class="font-semibold name font-cursive">miniGram</span>
    </a>

    <div class="w-full flex-grow sm:flex sm:items-center sm:w-auto block justify-end">
        <div>
            <div class="sm:flex-grow md:space-x-6 flex">
                @guest
                    <li class="no-underline block mt-4 sm:inline-block sm:mt-0 font-sans hover:shadow-inner duration-300">
                        <a class="block px-8 py-2 focus:outline-none name font-serif"
                           href="{{ route('login') }}">Login</a>
                    </li>
                    <li class="no-underline block mt-4 sm:inline-block sm:mt-0 font-sans hover:shadow-inner duration-300">
                        <a class="block px-8 py-2 focus:outline-none name font-serif"
                           href="{{ route('register') }}">Register</a>
                    </li>

                @else
                    <li class="no-underline block mt-4 sm:inline-block sm:mt-0 font-sans hover:shadow-inner duration-300">
                        <a class="block px-8 py-2 focus:outline-none name font-serif"
                           href="{{  route('users.index') }}">Friends</a>
                    </li>

                    <li class="no-underline block mt-4 sm:inline-block sm:mt-0 font-sans hover:shadow-inner duration-300">
                        <a class="block px-8 py-2 focus:outline-none name font-serif"
                           href="{{ route('users.show', auth('web')->user()) }}">{{ auth('web')->user()->name }}</a>
                    </li>

                    <li class="no-underline block mt-4 sm:inline-block sm:mt-0 font-sans hover:shadow-inner duration-300">
                        <a class="block px-8 py-2 focus:outline-none name font-serif" href="{{ route('logout') }}"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                        <form id="logout-form"
                              action="{{ action([\App\Http\Controllers\Auth\LoginController::class, 'logout']) }}"
                              method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endguest
            </div>
        </div>
    </div>
</nav>